version: "3.9"
networks:
  mysql:
    name: mysql
    external: true
services:
  api:
    container_name: dinesafe-api
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - mysql
