version: "3.9"
services:
  ui:
    container_name: dinesafe-ui
    build: .
    ports:
      - "8501:8501"
    entrypoint: "sh start_ui.sh"
    restart: unless-stopped
    depends_on:
      - api
  api:
    container_name: dinesafe-api
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - mysql
  mysql:
    container_name: dinesafe-mysql
    image: mysql
    env_file:
      - .env
    restart: unless-stopped
