version: "3.9"
services:
  ui:
    container_name: ui
    build: .
    ports:
      - "8501:8501"
    entrypoint: "sh start_ui.sh"
    restart: unless-stopped
    depends_on:
      - api
  api:
    container_name: api
    build: .
    ports:
      - "8000:8000"
    environment:
      - "API_KEY=???"
      - "MYSQL_URL=mysql"
      - "MYSQL_USER=root"
      - "MYSQL_PASSWORD=mysql_root_password"
    restart: unless-stopped
    depends_on:
      - mysql
  mysql:
    container_name: mysql
    image: mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=mysql_root_password"
    restart: unless-stopped
